### PR TITLE
Replace Sodexo with Ikea

### PR DESCRIPTION
**Pull request by anandsaw**
The option Sodexo has been replaced with Ikea.

### CODE REVIEW

**Comment by VHellendoorn** [comment]
No way, Sodexo is the bestests

**Comment by anandsaw** [comment]
I don't think that the food served up by Sodexo can be considered o be food at all.

**Comment by VHellendoorn** [comment]
It served an important function on our "exclusion" list for this reason

**Comment by anandsaw** [comment]
Well, I feel that Ikea deserves to be on this list as it is a viable option.

**Comment by anandsaw** [comment]
Besides, Burger King will never go away.

**Comment by VHellendoorn** [comment]
Fiiine

**Pull request merged**
